### ISSUE TITLE
ArrayableInterface not found

### ISSUE THREAD

**Issue by nWidart** [pingpong-labs/menus#14]
Hi,
I'm getting this error in Laravel 5.

``` php
Interface 'Illuminate\Support\Contracts\ArrayableInterface' not found 
```

With the following code:

``` php
Menu::create('main', function(Builder $menu)
        {
            $menu->url('products', 'Products');
        });
```

**Comment by eagerNewb** [comment]
Have the same issue on Laravel 5..any help?

**Comment by eagerNewb** [comment]
i think it has something to do with folder path to the Arrayable interface:
it is located in  ....../contracts/support but the admin is looking for it  in ..../support/contracts
