### ISSUE TITLE
'BadMethodCallException'

### ISSUE THREAD

**Issue by assoft** [pingpong-labs/menus#16]
php artisan vendor:publish
<code>exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /l5/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:226
Stack trace:
#0 /l5/vendor/pingpong/menus/src/Pingpong/Menus/MenusServiceProvider.php(21): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /l5/vendor/pingpong/menus/src/Pingpong/Menus/MenusServiceProvider.php(21): Pingpong\Menus\MenusServiceProvider->package('pingpong/menus')
#2 [internal function]: Pingpong\Menus\MenusServiceProvider->boot()
#3 /l5/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(624): Illuminate\Container\Container->call(Array)
#5 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Illuminate\Foundation\Application->bootProvider(Object(Pingpong\Menus\MenusServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Pingpong\Menus\MenusServiceProvider), 19)
#7 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(607): array_walk(Array, Object(Closure))
#8 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#9 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(158): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(180): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /l5/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /l5/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
</code>

**Comment by nWidart** [comment]
This package is probably not up to date with the latest L5 changes.

**Comment by harrisoftware** [comment]
php artisan config:publish pingpong/menus in documentation is wrong as well

**Comment by nWidart** [comment]
Indeed, it is now `php artisan vendor:publish` with an optional `--provider` flag.

**Comment by gravitano** [comment]
Fixed in version `~2.0`.
