### ISSUE TITLE
Ordering menu items

### ISSUE THREAD

**Issue by drparham** [pingpong-labs/menus#30]
When using `$menu->route` and order, the order is appended to the url in the browser. For instance this:
 ```
$menu->route(
        'dashboard.index', // route name
        'Dashboard', 1 // title
    );
```
results in this menu uri: `dashboard?1` That shouldn't show up. 

Also, when doing a drop down the documentation says to format the order like so: 
```
$menu->dropdown('Users', 4, function ($sub) {
        $sub->route('dashboard.users', 'Users');
        $sub->route('dashboard.roles', 'Roles');
        $sub->route('dashboard.permissions', 'Permissions');
    });
```
When it needs to be like this: 
```
$menu->dropdown('Users', function ($sub) {
        $sub->route('dashboard.users', 'Users');
        $sub->route('dashboard.roles', 'Roles');
        $sub->route('dashboard.permissions', 'Permissions');
    }, 4);
```
Order works properly in the `$menu->add` method.

**Comment by gravitano** [comment]
Oh, I am sorry for the wrong example in documentation page. I will fix that. For setting order key in `route` method, is in the 4th parameter.
```php
$menu->route(
        'dashboard.index', // route name
        'Dashboard', // title
        [], // route parameters
        1
    );
```

**Comment by drparham** [comment]
Great that resolved the issue, thanks!
